import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Add any head elements here if necessary */}
      </head>
      <body className={inter.className}>
        <Providers>
          <Sidebar listItems={[
            { label: 'Home', href: '/' },
            { label: 'Explore', href: '/' },
            { label: 'My Posts', href: '/' },
            { label: 'Profile', href: '/profile' },
          ]} />
          <div className="w-[95%] p-10 md:w-[70%] m-auto">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
